name: Auto update project wiki

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Initializes on any new tag

jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkouting main code...
        uses: actions/checkout@v3
      - name: Updating Project Wiki...
        uses: impresscms-dev/phpdocs-wiki-update-action@v2.2
        with:
          class_root_namespace: Imponeer\Smarty\Extensions\SunriseHTTPRouter\
          include: Imponeer\Smarty\Extensions\SunriseHTTPRouter\**
